### ISSUE TITLE
Great tool!

### ISSUE THREAD

**Issue by fubar** [remind101/ssm-env#20]
@remind101 this is a great tool! I wasn't happy with the complexity of the solutions for Kubernetes out there and this works nicely. Couple of notes on my experience setting this up, which you might find valuable to include in the readme:

1)
I am using this with a lightweight node alpine image, which does not include most CLI tools that are usually present on a Linux machine, such as curl. I am instead installing this tool like this in my Dockerfile:
```
RUN wget -O /usr/local/bin/ssm-env https://github.com/remind101/ssm-env/releases/download/v0.0.2/ssm-env
RUN chmod +x /usr/local/bin/ssm-env
```
It also does not come with root certificates which are needed by the go AWS SDK. This is easily fixed by adding:
```
RUN apk add --no-cache ca-certificates
```
to the Dockerfile as per https://simplydistributed.wordpress.com/2018/05/22/certificate-error-with-go-http-client-in-alpine-docker/

2)
For anyone using Kubernetes: As a one-time setup step for configuring AWS credentials, I ended up using Secrets:
```
kubectl create secret generic aws-credentials --from-literal=AWS_ACCESS_KEY_ID='AKIA...' --from-literal=AWS_SECRET_ACCESS_KEY='...'
```
and then using them in my deployment file like:
```
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: us-east-1
```
as per https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/

Thought this might help some folks.

Thanks for this tool!
